sudo: false
dist: trusty

language: ruby

rvm:
  - 2.6.5

notifications:
  email: false

matrix:
  fast_finish: true

before_install:
  - gem install bundler

script:
  - bundle exec rspec --format progress
